table 'Dim Customers'
	lineageTag: b60a3dc4-8e9f-4c3e-aa1f-25937b2cc050

	column 'Customer ID'
		dataType: string
		lineageTag: 923b418f-6de7-49b1-84b9-f15ee59aa589
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 9f3024c0-8760-458d-8058-4fc5b7e362cf
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e1853372-a6bd-4f59-b35e-51b65a3ead5e
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: e8f7d102-ed63-4648-a053-2b28647b934c
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Pincode
		dataType: int64
		formatString: 0
		lineageTag: 70dd3313-493a-4395-bfa3-9ff0c995b755
		summarizeBy: none
		sourceColumn: Pincode

		annotation SummarizationSetBy = Automatic

	column EmailID
		dataType: string
		lineageTag: 744356dd-da65-432d-a92d-9badabb213e2
		summarizeBy: none
		sourceColumn: EmailID

		annotation SummarizationSetBy = Automatic

	column 'Phone Number'
		dataType: int64
		formatString: 0
		lineageTag: 0368c3ad-3913-437f-acf2-6fca9c3f48bf
		summarizeBy: none
		sourceColumn: Phone Number

		annotation SummarizationSetBy = Automatic

	partition 'Dim Customers' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Admin\Desktop\PowerBI\Store+Data.xlsx"), null, true),
				    #"Dim Customers_Sheet" = Source{[Item="Dim Customers",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Dim Customers_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer ID", type text}, {"Customer Name", type text}, {"City", type text}, {"State", type text}, {"Pincode", Int64.Type}, {"EmailID", type text}, {"Phone Number", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

