table 'Dim Product'
	lineageTag: 7cc26c0b-900a-4822-9b4f-174cdb8b7f18

	column ProductID
		dataType: string
		lineageTag: 5aaeb7b9-234c-47fb-86bf-e5a9f4f0e1d8
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 57a1a093-0d5c-41f4-80b4-2e1dcbf16d86
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column 'Product Line'
		dataType: string
		lineageTag: af64c94f-11ac-41ba-9879-0de155b62226
		summarizeBy: none
		sourceColumn: Product Line

		annotation SummarizationSetBy = Automatic

	column 'Price Per Unit (INR)'
		dataType: int64
		formatString: 0
		lineageTag: c2cd265f-d5d8-4da1-844a-c47547802bea
		summarizeBy: none
		sourceColumn: Price Per Unit (INR)

		annotation SummarizationSetBy = Automatic

	partition 'Dim Product' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Admin\Desktop\PowerBI\Store+Data.xlsx"), null, true),
				    #"Dim Product_Sheet" = Source{[Item="Dim Product",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Dim Product_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductID", type text}, {"Product Name", type text}, {"Product Line", type text}, {"Price (INR)", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Price (INR)", "Price Per Unit (INR)"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

