table 'Fact Table'
	lineageTag: 5b93260a-3d79-440c-822f-88250594a31d

	column 'Date (dd/mm/yyyy)'
		dataType: dateTime
		formatString: Long Date
		lineageTag: fd005700-3f3d-46cb-8ca4-39661714bb56
		summarizeBy: none
		sourceColumn: Date (dd/mm/yyyy)

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: string
		lineageTag: 286cbe64-f23a-4252-b472-5001ac86ca5b
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column PromotionID
		dataType: string
		lineageTag: e6ac28d0-3058-4473-99c3-2dffc7df3570
		summarizeBy: none
		sourceColumn: PromotionID

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 1687e411-fd3e-4418-b831-ba183355b686
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: int64
		formatString: 0
		lineageTag: 932c9e6a-91e0-4e42-b571-11624ae7e991
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

	column 'Price Per Unit'
		dataType: int64
		formatString: 0
		lineageTag: ebef7673-2c43-4770-9125-f61c69322e53
		summarizeBy: sum
		sourceColumn: Price Per Unit

		annotation SummarizationSetBy = Automatic

	column 'Total Sales  '
		dataType: int64
		formatString: 0
		lineageTag: cd7bc5e7-5328-4222-a51b-86d8f23fdae8
		summarizeBy: sum
		sourceColumn: "Total Sales  "

		annotation SummarizationSetBy = Automatic

	column 'Discount Percentage'
		dataType: int64
		formatString: 0
		lineageTag: a61e100b-b797-4036-a179-58cc5494101c
		summarizeBy: sum
		sourceColumn: Discount Percentage

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 2db9c310-8ad5-4a2d-9999-88f1c6ba470c
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Net Sales  '
		dataType: double
		lineageTag: af57e4ab-2a26-46d8-9872-05eb6b84dcee
		summarizeBy: sum
		sourceColumn: "Net Sales  "

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: d6186d23-d8af-4c1b-adcd-1192d1b60882
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderID
		dataType: string
		lineageTag: 2b9d5f9c-4f2b-4081-beac-cef441ac5e3e
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	partition 'Fact Table' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Admin\Desktop\PowerBI\Store+Data.xlsx"), null, true),
				    Sheet3_Sheet = Source{[Item="Sheet3",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet3_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date (dd/mm/yyyy)", type date}, {"CustomerID", type text}, {"PromotionID", type text}, {"Product ID", type text}, {"Units Sold", Int64.Type}, {"Price Per Unit", type any}, {"Total Sales", type any}, {"Discount Percentage", type any}, {"Discount Value", type any}, {"Net Sales", type any}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"Product ID"}, #"Dim Product", {"ProductID"}, "Dim Product", JoinKind.LeftOuter),
				    #"Expanded Dim Product" = Table.ExpandTableColumn(#"Merged Queries", "Dim Product", {"Price Per Unit (INR)"}, {"Dim Product.Price Per Unit (INR)"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded Dim Product",{"Price Per Unit"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Dim Product.Price Per Unit (INR)", "Price Per Unit"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales", "Discount Percentage", "Discount Value", "Net Sales"}),
				    #"Added Custom" = Table.AddColumn(#"Reordered Columns", "Total Sales  ", each [Price Per Unit] * [Units Sold]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Total Sales  ", Int64.Type}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Changed Type1",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales  ", "Total Sales", "Discount Percentage", "Discount Value", "Net Sales"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns1",{"Total Sales"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Columns1", each true),
				    #"Merged Queries1" = Table.NestedJoin(#"Filtered Rows1", {"PromotionID"}, #"Dim Promotion", {"PromotionID"}, "Dim Promotion", JoinKind.LeftOuter),
				    #"Expanded Dim Promotion" = Table.ExpandTableColumn(#"Merged Queries1", "Dim Promotion", {"Percentage"}, {"Dim Promotion.Percentage"}),
				    #"Filtered Rows2" = Table.SelectRows(#"Expanded Dim Promotion", each true),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows2",null,0,Replacer.ReplaceValue,{"Dim Promotion.Percentage"}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Replaced Value",{"Discount Percentage"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns2",{{"Dim Promotion.Percentage", "Discount Percentage"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Discount Percentage", Int64.Type}}),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Changed Type2",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales  ", "Discount Percentage", "Discount Value", "Net Sales"}),
				    #"Added Custom1" = Table.AddColumn(#"Reordered Columns2", "Discount", each ([#"Total Sales  "] * [Discount Percentage])/100),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom1",{{"Discount", type number}}),
				    #"Reordered Columns3" = Table.ReorderColumns(#"Changed Type3",{"Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales  ", "Discount Percentage", "Discount", "Discount Value", "Net Sales"}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Reordered Columns3",{"Discount Value"}),
				    #"Added Custom2" = Table.AddColumn(#"Removed Columns3", "Net Sales  ", each [#"Total Sales  "] - [Discount]),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom2",{{"Net Sales  ", type number}}),
				    #"Removed Columns4" = Table.RemoveColumns(#"Changed Type4",{"Net Sales"}),
				    #"Added Custom3" = Table.AddColumn(#"Removed Columns4", "Profit", each 0.1 * [#"Net Sales  "]),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom3",{{"Profit", type number}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type5", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns4" = Table.ReorderColumns(#"Added Index",{"Index", "Date (dd/mm/yyyy)", "CustomerID", "PromotionID", "Product ID", "Units Sold", "Price Per Unit", "Total Sales  ", "Discount Percentage", "Discount", "Net Sales  ", "Profit"}),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Reordered Columns4",{{"Index", type text}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type6",{{"Index", "OrderID"}})
				in
				    #"Renamed Columns2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

